# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f79cc176b0ac111fb07d67b11904b1e4815c218a3e80af19e56501272588b8a9e71409591a114918ec232ff28b8d5a735a4e34a05079ef47c1453656615d2e65

test:
  secret_key_base: a402dc596fb994e81593bfeba59e2c4a8e3ed003ff285e755cec7f9ecb1ab54fa99a0a44d15408d5e2dc6fbd808bbdcc4cda190063d86c8051cd38b4ce98c560

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
